### Seleccionar orden
GET http://localhost:4004/manage-orders/GetOrders

### Crear orden
POST http://localhost:4004/manage-orders/CreaOrders HTTP/1.1
Content-Type: application/json

{            
"Email": "email_prueba@prueba.es",
"FirstName": "David",
"LastName": "Garcia",
"Country": "España",
"CreatedOn": "2023-03-28",
"OrderStatus": 1,
"DeliveryDate": "2023-03-28",
"ImageUrl": "/orders/webapp/assets/cliente_hombre_1.png"
}

### Borrar orden
DELETE http://localhost:4004/manage-orders/DelOrders('1')

### Actualizar orden
PUT http://localhost:4004/manage-orders/SetOrders('1') HTTP/1.1
Content-Type: application/json

{
   "OrderStatus": 1
}



